cmake_minimum_required(VERSION 3.17)

project(archtest)

set(CMAKE_CXX_STANDARD 17)


#####libarchive start#####
find_package(OpenSSL REQUIRED)

macro(SET_OPTION option value)
  set(${option} ${value} CACHE INTERNAL "" FORCE)
endmacro()

SET_OPTION(BUILD_SHARED_LIBS  OFF)
SET_OPTION(ENABLE_NETTLE  OFF)
SET_OPTION(ENABLE_OPENSSL  ON)
SET_OPTION(ENABLE_LZ4  OFF)
SET_OPTION(ENABLE_LZO  OFF)
SET_OPTION(ENABLE_LZMA  OFF)

SET_OPTION(ENABLE_ZLIB  OFF)
SET_OPTION(ENABLE_BZip2  OFF)
SET_OPTION(ENABLE_LIBXML2 OFF)
SET_OPTION(ENABLE_EXPAT OFF)
SET_OPTION(ENABLE_PCREPOSIX OFF)
SET_OPTION(ENABLE_LibGCC OFF)
SET_OPTION(ENABLE_CNG OFF)

SET_OPTION(ENABLE_TAR OFF)
SET_OPTION(ENABLE_CPIO OFF)
SET_OPTION(ENABLE_CAT OFF)
SET_OPTION(ENABLE_XATTR ON)
SET_OPTION(ENABLE_ACL OFF)
SET_OPTION(ENABLE_ICONV OFF)
SET_OPTION(ENABLE_TEST OFF)
SET_OPTION(ENABLE_COVERAGE OFF)
SET_OPTION(ENABLE_INSTALL OFF)
SET_OPTION(ENABLE_LIBXML2 OFF)

add_subdirectory(3rdparty/libarchive EXCLUDE_FROM_ALL)
#####libarchive end#####

add_executable(${PROJECT_NAME} src/main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE archive)
